// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Url struct {
	ID            int64
	Url           interface{}
	Title         interface{}
	VisitCount    int64
	TypedCount    int64
	LastVisitTime int64
	Hidden        int64
}

type Visit struct {
	ID                           int64
	Url                          int64
	VisitTime                    int64
	FromVisit                    sql.NullInt64
	ExternalReferrerUrl          sql.NullString
	Transition                   int64
	SegmentID                    sql.NullInt64
	VisitDuration                int64
	IncrementedOmniboxTypedScore bool
	OpenerVisit                  sql.NullInt64
	OriginatorCacheGuid          sql.NullString
	OriginatorVisitID            sql.NullInt64
	OriginatorFromVisit          sql.NullInt64
	OriginatorOpenerVisit        sql.NullInt64
	IsKnownToSync                bool
	ConsiderForNtpMostVisited    bool
	VisitedLinkID                int64
	AppID                        sql.NullString
}
