// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getVisits = `-- name: GetVisits :many
SELECT visits.visit_time, urls.last_visit_time, urls.url, urls.title, urls.visit_count
FROM urls, visits
WHERE visits.url = urls.id
ORDER BY visit_time DESC
`

type GetVisitsRow struct {
	VisitTime     int64
	LastVisitTime int64
	Url           interface{}
	Title         interface{}
	VisitCount    int64
}

func (q *Queries) GetVisits(ctx context.Context) ([]GetVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitsRow
	for rows.Next() {
		var i GetVisitsRow
		if err := rows.Scan(
			&i.VisitTime,
			&i.LastVisitTime,
			&i.Url,
			&i.Title,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
