// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_ff

import (
	"database/sql"
)

type MozHistoryvisit struct {
	ID                int64
	FromVisit         sql.NullInt64
	PlaceID           sql.NullInt64
	VisitDate         sql.NullInt64
	VisitType         sql.NullInt64
	Session           sql.NullInt64
	Source            int64
	Triggeringplaceid sql.NullInt64
}

type MozHistoryvisitsExtra struct {
	VisitID  int64
	SyncJson sql.NullString
}

type MozPlace struct {
	ID                int64
	Url               interface{}
	Title             interface{}
	RevHost           interface{}
	VisitCount        sql.NullInt64
	Hidden            int64
	Typed             int64
	Frecency          int64
	LastVisitDate     sql.NullInt64
	Guid              sql.NullString
	ForeignCount      int64
	UrlHash           int64
	Description       sql.NullString
	PreviewImageUrl   sql.NullString
	SiteName          sql.NullString
	OriginID          sql.NullInt64
	RecalcFrecency    int64
	AltFrecency       sql.NullInt64
	RecalcAltFrecency int64
}
