// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc_ff

import (
	"context"
	"database/sql"
)

const getVisits = `-- name: GetVisits :many
SELECT moz_historyvisits.visit_date, moz_places.last_visit_date, moz_places.url, moz_places.title, moz_places.visit_count
FROM moz_historyvisits, moz_places
WHERE moz_historyvisits.place_id = moz_places.id
ORDER BY moz_historyvisits.visit_date DESC
`

type GetVisitsRow struct {
	VisitDate     sql.NullInt64
	LastVisitDate sql.NullInt64
	Url           interface{}
	Title         interface{}
	VisitCount    sql.NullInt64
}

func (q *Queries) GetVisits(ctx context.Context) ([]GetVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitsRow
	for rows.Next() {
		var i GetVisitsRow
		if err := rows.Scan(
			&i.VisitDate,
			&i.LastVisitDate,
			&i.Url,
			&i.Title,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
